version: "3"

volumes:
  djwebhooks_local_postgres_data: {}
  djwebhooks_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: djwebhooks_local_django
    container_name: djwebhooks_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: djwebhooks_production_postgres
    container_name: djwebhooks_local_postgres
    volumes:
      - djwebhooks_local_postgres_data:/var/lib/postgresql/data
      - djwebhooks_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: djwebhooks_local_docs
    container_name: djwebhooks_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./apps:/app/apps:z
    ports:
      - "9000:9000"
    command: /start-docs

  mailpit:
    image: axllent/mailpit:v1.8
    container_name: djwebhooks_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: djwebhooks_local_redis

  celeryworker:
    <<: *django
    image: djwebhooks_local_celeryworker
    container_name: djwebhooks_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: djwebhooks_local_celerybeat
    container_name: djwebhooks_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: djwebhooks_local_flower
    container_name: djwebhooks_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
