# Generated by Django 4.2.5 on 2023-09-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookPayload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payload", models.JSONField()),
                ("success", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Webhook Payload",
                "verbose_name_plural": "Webhook Payloads",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["created_at"], name="webhooks_we_created_3407eb_idx")],
            },
        ),
    ]
